// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiz-BOX4gIZ-k5QT817AvUQvs94MPncDc',
    appId: '1:700178322429:web:7a2286c17fa4742c9d3f94',
    messagingSenderId: '700178322429',
    projectId: 'species-iiap',
    authDomain: 'species-iiap.firebaseapp.com',
    storageBucket: 'species-iiap.appspot.com',
    measurementId: 'G-PMYC2S26KG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjF9-DuU0-f0-MbOKgbBDcjQ5ofyOS4aE',
    appId: '1:700178322429:android:abb59f5248ac72d39d3f94',
    messagingSenderId: '700178322429',
    projectId: 'species-iiap',
    storageBucket: 'species-iiap.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5agPnSqau0Xxo_49hdsjZkr37sqLPJ68',
    appId: '1:700178322429:ios:46fc7b7ba74f242f9d3f94',
    messagingSenderId: '700178322429',
    projectId: 'species-iiap',
    storageBucket: 'species-iiap.appspot.com',
    iosClientId: '700178322429-k230b69odvuu4j57qsnmcji5b7k2ot8h.apps.googleusercontent.com',
    iosBundleId: 'pe.gob.iiap.species',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5agPnSqau0Xxo_49hdsjZkr37sqLPJ68',
    appId: '1:700178322429:ios:bf5a9a98ef44f31f9d3f94',
    messagingSenderId: '700178322429',
    projectId: 'species-iiap',
    storageBucket: 'species-iiap.appspot.com',
    iosClientId: '700178322429-rfvgf1b5alubf1cs0tioqbbrdei69gsr.apps.googleusercontent.com',
    iosBundleId: 'pe.gob.iiap.species.RunnerTests',
  );
}
